sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET FullAccession = ltrim(FullAccession, '|')"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET FullAccession = ltrim(substr(FullAccession, instr(FullAccession, '|')))"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET FullAccession = ltrim(FullAccession, '|')"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET FullAccession = ltrim(substr(FullAccession, instr(FullAccession, '|')))"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET FullAccession = ltrim(FullAccession, '|')"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET UniprotSearchString = ltrim(UniprotSearchString, '|')"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET UniprotSearchString = ltrim(substr(UniprotSearchString, instr(UniprotSearchString, '|')))"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET UniprotSearchString = ltrim(UniprotSearchString, '|')"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET UniprotSearchString = ltrim(substr(UniprotSearchString, instr(UniprotSearchString, '|')))"
sqlite3 Trinotate.sqlite "UPDATE BlastDbase SET UniprotSearchString = ltrim(UniprotSearchString, '|')"
sqlite3 Trinotate.sqlite "CREATE INDEX blast_idx on BlastDbase(FullAccession, QueryStart, QueryEnd, HitStart, HitEnd, PercentIdentity, HitCoverage, Evalue)"
sqlite3 Trinotate.sqlite "CREATE INDEX blastID_idx ON BlastDbase(TrinityID);"